# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  
# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

# get elements less than 4 million
fib_seq <- c(1, 2)
n1 <- 1
n2 <- 2
n3 <- n1 + n2

while (n3 <= 4000000) {
  
  fib_seq <- append(fib_seq, n3)
  n1 <- n2
  n2 <- n3
  n3 <- n1 + n2

}

# pick out even terms only
even_terms <- c()

for (i in seq_along(fib_seq)) {
  
  if (fib_seq[i] %% 2 == 0) {
    even_terms <- append(even_terms, fib_seq[i])
  }
 
 }

sum(even_terms)
